apiVersion: v1
kind: Service 
metadata: 
  name: svc-sistema-noticias
spec: 
  type: NodePort
  selector:
    app: sistemas-noticias
  ports:
    - port: 80
      #Intuituvamente define-se o targetPort:80
      nodePort: 30001